[package]
name = "src"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
actix-cors = "0.6.4"
proj = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
env_logger = "0.9.3"
flate2 = "1.0.25"
image = "0.24.5"
base64 = "0.13.1"
